#define MIN_CALLEE_NUM 3
#define MAX_CALLEE_NUM 10
#define MAX_USER_NUM 2000
#define MAX_USER_NAME_LEN 20

#define MAX_APPOINTMENT_NUM 20000

#define START_HOUR 18
#define END_HOUR 21
#define SLOT_PER_HOUR 1


#define PRIVATE_TIME_TYPE 4
#define PROJECT_MEETING_TYPE 3
#define GROUP_STUDY_TYPE 2
#define GATHERING_TYPE 1