#ifndef COMMON_H
#define COMMON_H

#define MIN_CALLEE_NUM 3
#define MAX_CALLEE_NUM 10
#define MAX_USER_NUM 20
#define MAX_USER_NAME_LEN 20

#define INF 1000000000

#define MAX_APPOINTMENT_NUM 20000

#define START_HOUR 18
#define END_HOUR 23
#define SLOT_PER_HOUR 1
#define SLOT_PER_DAY ((END_HOUR-START_HOUR)*SLOT_PER_HOUR)
#define MAX_DAY_NUM 30000

#define PRIVATE_TIME_TYPE 4
#define PROJECT_MEETING_TYPE 3
#define GROUP_STUDY_TYPE 2
#define GATHERING_TYPE 1

#define SCHD_NUM 4


#endif